# ============================================================================
# Extraccion de datos ICFES desde BigQuery -> Parquet
# Ejecutar UNA VEZ para generar los archivos .parquet en datos/
# Requiere: bigrquery, arrow, dplyr
# ============================================================================

library(bigrquery)
library(arrow)
library(dplyr)

proyecto_bq <- "ph-jabri"

# --- Saber Pro ---------------------------------------------------------------
cat("Extrayendo Saber Pro...\n")
sql_saber_pro <- "
 SELECT
    ESTU_CONSECUTIVO,
    PERIODO,
    -- Sociodemográficas
    ESTU_GENERO,
    ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE,
    ESTU_MCPIO_RESIDE,
    ESTU_AREARESIDE ESTU_ZONA_RESIDE,
    
    FAMI_ESTRATOVIVIENDA,
    
    FAMI_EDUCACIONPADRE,
    FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET,
    FAMI_TIENECOMPUTADOR,
    FAMI_TIENEAUTOMOVIL,
    FAMI_TIENELAVADORA,
    
    -- Institución
    INST_NOMBRE_INSTITUCION,
    
    
    INST_ORIGEN,
    INST_CARACTER_ACADEMICO,
    ESTU_METODO_PRGM,
    
    ESTU_PRGM_ACADEMICO,
    ESTU_SNIES_PRGMACADEMICO,
    -- Puntajes módulos genéricos
    MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT,
    MOD_COMPETEN_CIUDADA_PUNT,
    MOD_INGLES_PUNT,
    
    MOD_INGLES_DESEM,
    PUNT_GLOBAL
  FROM `ph-jabri.SABER_PRO.SBPRO_2018`
  UNION ALL SELECT * FROM (
    SELECT ESTU_CONSECUTIVO, PERIODO, ESTU_GENERO, ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE, ESTU_AREARESIDE ESTU_ZONA_RESIDE, 
    FAMI_ESTRATOVIVIENDA,  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET, FAMI_TIENECOMPUTADOR, FAMI_TIENEAUTOMOVIL,
  FAMI_TIENELAVADORA,
     INST_NOMBRE_INSTITUCION, 
  
    INST_ORIGEN, INST_CARACTER_ACADEMICO, ESTU_METODO_PRGM, 
    ESTU_PRGM_ACADEMICO, ESTU_SNIES_PRGMACADEMICO, MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT, MOD_COMPETEN_CIUDADA_PUNT, MOD_INGLES_PUNT,
     MOD_INGLES_DESEM, PUNT_GLOBAL
    FROM `ph-jabri.SABER_PRO.SBPRO_2019`
  )
  UNION ALL SELECT * FROM (
    SELECT ESTU_CONSECUTIVO, PERIODO, ESTU_GENERO, ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE, ESTU_AREARESIDE ESTU_ZONA_RESIDE, 
    FAMI_ESTRATOVIVIENDA,  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET, FAMI_TIENECOMPUTADOR, FAMI_TIENEAUTOMOVIL,
  FAMI_TIENELAVADORA,
     INST_NOMBRE_INSTITUCION, 
  
    INST_ORIGEN, INST_CARACTER_ACADEMICO, ESTU_METODO_PRGM, 
    ESTU_PRGM_ACADEMICO, ESTU_SNIES_PRGMACADEMICO, MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT, MOD_COMPETEN_CIUDADA_PUNT, MOD_INGLES_PUNT,
     MOD_INGLES_DESEM, PUNT_GLOBAL
    FROM `ph-jabri.SABER_PRO.SBPRO_2020`
  )
  UNION ALL SELECT * FROM (
    SELECT ESTU_CONSECUTIVO, PERIODO, ESTU_GENERO, ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE, ESTU_AREARESIDE ESTU_ZONA_RESIDE, 
    FAMI_ESTRATOVIVIENDA,  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET, FAMI_TIENECOMPUTADOR, FAMI_TIENEAUTOMOVIL,
  FAMI_TIENELAVADORA,
     INST_NOMBRE_INSTITUCION, 
  
    INST_ORIGEN, INST_CARACTER_ACADEMICO, ESTU_METODO_PRGM, 
    ESTU_PRGM_ACADEMICO, ESTU_SNIES_PRGMACADEMICO, MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT, MOD_COMPETEN_CIUDADA_PUNT, MOD_INGLES_PUNT,
     MOD_INGLES_DESEM, PUNT_GLOBAL
    FROM `ph-jabri.SABER_PRO.SBPRO_2021`
  )
  UNION ALL SELECT * FROM (
    SELECT ESTU_CONSECUTIVO, PERIODO, ESTU_GENERO, ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE,ESTU_AREARESIDE  ESTU_ZONA_RESIDE, 
    FAMI_ESTRATOVIVIENDA,  FAMI_EDUCACIONPADRE,
  FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET, FAMI_TIENECOMPUTADOR, FAMI_TIENEAUTOMOVIL,
  FAMI_TIENELAVADORA,
     INST_NOMBRE_INSTITUCION, 
  
    INST_ORIGEN, INST_CARACTER_ACADEMICO, ESTU_METODO_PRGM, 
    ESTU_PRGM_ACADEMICO, ESTU_SNIES_PRGMACADEMICO, MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT, MOD_COMPETEN_CIUDADA_PUNT, MOD_INGLES_PUNT,
     MOD_INGLES_DESEM, PUNT_GLOBAL
    FROM `ph-jabri.SABER_PRO.SBPRO_20221`
  )
  UNION ALL SELECT * FROM (
    SELECT ESTU_CONSECUTIVO, PERIODO, ESTU_GENERO, ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE, ESTU_MCPIO_RESIDE, ESTU_AREARESIDE ESTU_ZONA_RESIDE,
    FAMI_ESTRATOVIVIENDA, FAMI_EDUCACIONPADRE, FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET, FAMI_TIENECOMPUTADOR, FAMI_TIENEAUTOMOVIL,
    CAST(NULL AS STRING) AS FAMI_TIENELAVADORA,
    CAST(NULL AS STRING) AS INST_NOMBRE_INSTITUCION,
    INST_ORIGEN, INST_CARACTER_ACADEMICO, ESTU_METODO_PRGM,
    ESTU_PRGM_ACADEMICO, ESTU_SNIES_PRGMACADEMICO, MOD_RAZONA_CUANTITAT_PUNT,
    MOD_LECTURA_CRITICA_PUNT, MOD_COMPETEN_CIUDADA_PUNT, MOD_INGLES_PUNT,
    MOD_INGLES_DESEM, PUNT_GLOBAL
    FROM `ph-jabri.SABER_PRO.SBPRO_20222`
  ) 

"
saber_pro <- bq_project_query(proyecto_bq, sql_saber_pro) |>
  bq_table_download()
write_parquet(saber_pro, "saber_pro/saber_pro.parquet")
cat("  -> saber_pro/saber_pro.parquet guardado:", nrow(saber_pro), "filas\n")

# --- Saber 11 ----------------------------------------------------------------
cat("Extrayendo Saber 11...\n")
sql_saber11 <- "
SELECT
    ESTU_CONSECUTIVO,
    PERIODO,
    -- Sociodemográficas
    ESTU_GENERO,
    ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE,
    ESTU_MCPIO_RESIDE,
    ESTU_AREARESIDE ESTU_ZONA_RESIDE,
    ESTU_NSE_INDIVIDUAL,
    ESTU_PRIVADO_LIBERTAD,
    FAMI_ESTRATOVIVIENDA,
    FAMI_PERSONASHOGAR,
    FAMI_EDUCACIONPADRE,
    FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET,
    FAMI_TIENECOMPUTADOR,
    FAMI_TIENEAUTOMOVIL,
    FAMI_TIENELAVADORA,
    FAMI_NUMLIBROS,
    -- Colegio
    COLE_NOMBRE_ESTABLECIMIENTO,
    COLE_DEPTO_UBICACION,
    COLE_MCPIO_UBICACION,
    COLE_NATURALEZA,
    COLE_CALENDARIO,
    COLE_JORNADA,
    COLE_GENERO,
    COLE_AREA_UBICACION,
    -- Puntajes
    PUNT_GLOBAL,
    PUNT_MATEMATICAS,
    PUNT_LECTURA_CRITICA,
    PUNT_C_NATURALES,
    PUNT_SOCIALES_CIUDADANAS,
    PUNT_INGLES,
    DESEMP_INGLES
  FROM `ph-jabri.SABER11.SB11_20151`
  UNION ALL
  SELECT
    ESTU_CONSECUTIVO,
    PERIODO,
    ESTU_GENERO,
    ESTU_FECHANACIMIENTO,
    ESTU_DEPTO_RESIDE,
    ESTU_MCPIO_RESIDE,
    ESTU_AREARESIDE ESTU_ZONA_RESIDE,
    ESTU_NSE_INDIVIDUAL,
    ESTU_PRIVADO_LIBERTAD,
    FAMI_ESTRATOVIVIENDA,
    FAMI_PERSONASHOGAR,
    FAMI_EDUCACIONPADRE,
    FAMI_EDUCACIONMADRE,
    FAMI_TIENEINTERNET,
    FAMI_TIENECOMPUTADOR,
    FAMI_TIENEAUTOMOVIL,
    FAMI_TIENELAVADORA,
    FAMI_NUMLIBROS,
    COLE_NOMBRE_ESTABLECIMIENTO,
    COLE_DEPTO_UBICACION,
    COLE_MCPIO_UBICACION,
    COLE_NATURALEZA,
    COLE_CALENDARIO,
    COLE_JORNADA,
    COLE_GENERO,
    COLE_AREA_UBICACION,
    PUNT_GLOBAL,
    PUNT_MATEMATICAS,
    PUNT_LECTURA_CRITICA,
    PUNT_C_NATURALES,
    PUNT_SOCIALES_CIUDADANAS,
    PUNT_INGLES,
    DESEMP_INGLES
  FROM `ph-jabri.SABER11.SB11_20152`
  
"
saber11 <- bq_project_query(proyecto_bq, sql_saber11) |>
  bq_table_download()
write_parquet(saber11, "saber11/saber11.parquet")
cat("  -> saber11/saber11.parquet guardado:", nrow(saber11), "filas\n")

# --- Cruce Saber11 - SaberPro ------------------------------------------------
cat("Extrayendo cruce Saber11-SaberPro...\n")
sql_cruce <- "SELECT * FROM `ph-jabri.ICFES.Saber11_SaberPro`"
cruce <- bq_project_query(proyecto_bq, sql_cruce) |>
  bq_table_download()
write_parquet(cruce, "cruce/cruce_saber11_saberpro.parquet")
cat("  -> cruce/cruce_saber11_saberpro.parquet guardado:", nrow(cruce), "filas\n")

cat("\nExtraccion completa. Archivos .parquet listos para subir al repositorio.\n")
